### ISSUE TITLE
自定义指令无权限

### ISSUE THREAD

**Issue by GuYuan-V** [TRCStudioDean/LiteCommandEditor#2]
<img width="523" alt="Snipaste_2024-07-25_17-34-46" src="https://github.com/user-attachments/assets/a47adfc8-575a-48f5-94ea-dea892e854a6">
指令为/fp ，正常使用没有问题，使用修改后的的简化命令提示无权限如图，可是原命令可以正常使用

**Comment by TRCStudioDean** [comment]
配置文件提供一下

**Comment by GuYuan-V** [comment]
[Alias.txt](https://github.com/user-attachments/files/16379256/Alias.txt)
[Config.txt](https://github.com/user-attachments/files/16379259/Config.txt)

**Comment by GuYuan-V** [comment]
#命令别名设置
#本选项可用于设置命令的使用别名
#以使命令的使用更加简便
#格式:（支持中文）
#   [命令别名]: [原命令]
#   [命令前缀]:[命令别名]: [原命令]
#若不填写命令前缀，则默认为“litecommandeditor”
#按照此格式可自由添加新的命令别名
#注意：建议在更改设置后重启服务器
Aliases:
    #/litecommandeditor reload -> /lcereload
    "lcereload": "litecommandeditor reload"
    #/litecommandeditor info -> /lceinfo
    "lceinfo": "litecommandeditor info"
    #/litecommandeditor load -> /lceload
    "lceload": "litecommandeditor load"
    #/litecommandeditor unload -> /lceunload
    "lceunload": "litecommandeditor unload"
    #/litecommandeditor list -> /lcelist
    "lcelist": "litecommandeditor list"
    #/litecommandeditor listall -> /lcelistall
    "lcelistall": "litecommandeditor listall"
    #/tpaccept
    "yes": "tpaccept"
    "同意": "tpaccept"
    "y": "tpaccept"
    #/tpdeny
    "n": "tpdeny"
    "no": "tpdeny"
    "拒绝": "tpdeny"
    #/la view help
    "ushelp": "la view help"
    "cnhelp": "la view cnhelp"
    #/tpacancel
    "off": "tpacancel"
    "取消": "tpacancel"
    #/fp spawn
    minecraft:setjr: fp spawn
    "创建假人": "fp spawn"
    #/fp kill
    "offjr": "fp kill"
    "清除假人": "fp kill"
    #/tab player 
    "qtab": "tab player"
    #/fp status
    "lookjr": "fp status"
    "查看假人": "fp status"

**Comment by GuYuan-V** [comment]
[Alias.txt](https://github.com/user-attachments/files/16379277/Alias.txt)

[Config.txt](https://github.com/user-attachments/files/16379278/Config.txt)

**Comment by GuYuan-V** [comment]
`#插件前缀
Prefix: '&bLite&3Command&9Editor &f&l>>> '

#插件语言
#可用语言: Simplified-Chinese（简体中文）、Traditional-Chinese（繁體中文）、English
Language: Simplified-Chinese

#禁用的命令
#禁用后，命令将无法使用（命令将不存在），直到下次重启服务器才会重新判断。
#注意：禁用其他插件的命令可能会发生严重的后果，谨慎使用！
#格式：[命令前缀]:[命令名]
#示例：bukkit:plugins 即可禁用/plugins命令
#如果想要知道命令的前缀，可以使用 /litecommandeditor info [命令] 查看。
Disabled-Commands: []

#执行命令的冷却（单位：秒）
#在这里写上需要添加冷却的命令，可以防止玩家频繁执行命令。
#注意，本功能的判断逻辑是：当玩家输入的命令以列表中的某个命令为开头，就会被添加冷却
#此设置中的命令，其主命令的源头的所有命令别名（包括带前缀的命令）均会添加冷却。
#例如: 为"lce"命令设置冷却时间时，将使 "litecommandeditor:lce", "litecommandeditor:litecommandeditor" 等本插件的所有命令别名都添加相同的冷却时间
#此选项对其他插件的命令也能够生效
Commands-Cooldown:
    Enabled: true
    #命令列表，格式为：“[命令]:[冷却时间]”
    List: 
    - 'examplecommand compound': 1.0 #即玩家输入 "/examplecommand compound ..." 时就会触发1秒冷却
    
#异步线程的设置
#若不清楚这什么是异步线程，请不要修改这个选项！
Async-Thread-Settings: 
    #每一刻的延迟（单位是秒，可以有小数）
    #例：0.1为每秒执行10次，0.05为每秒执行20次，即 20 TPS
    Tick-Delay: 0.1
    #是否自动移除重复的延时任务（延时任务是指包含Delay设置并且在线程池上运行的任务）
    #启用此选项后，以下任务将在重复运行时将移除当前未完成的延时任务:
    #1. ActionBar 动作栏消息（文字动画）
    #2. Title 标题消息（文字动画）
    #3. ClientSound 播放声音（播放乐谱）
    #4. CompoundFunction 复合函数（函数的执行）
    Remove-Duplicate-Delayed-Tasks: true

#计算保留的小数位数
Retaining-Decimal-Places: 2

#PlaceholderAPI设置
PlaceholderAPI:
    #是否使用
    Enabled: true
    #占位符缓存更新的延迟（秒）
    #由于部分占位符需要不断地读取数据库的数据，
    #此选项用于防止频繁调用PAPI占位符对数据库IO造成的巨大负担
    Cache-Update-Delay: 10.0
    #例外的占位符（不进行缓存的）
    Exceptions: []

#是否检查更新
#每天一次，将自动检测插件的最新版本及信息，并汇报给控制台及有拥有对应权限的玩家
#此功能并不会造成服务器产生过多流量（每次检测产生约不到1kb网络流量）
Updater: true

#是否启用Metrics
#详见https://bstats.org/plugin/bukkit/LiteCommandEditor/
Metrics: true`

**Comment by GuYuan-V** [comment]
> #插件前缀
Prefix: '&bLite&3Command&9Editor &f&l>>> '

#插件语言
#可用语言: Simplified-Chinese（简体中文）、Traditional-Chinese（繁體中文）、English
Language: Simplified-Chinese

#禁用的命令
#禁用后，命令将无法使用（命令将不存在），直到下次重启服务器才会重新判断。
#注意：禁用其他插件的命令可能会发生严重的后果，谨慎使用！
#格式：[命令前缀]:[命令名]
#示例：bukkit:plugins 即可禁用/plugins命令
#如果想要知道命令的前缀，可以使用 /litecommandeditor info [命令] 查看。
Disabled-Commands: []

#执行命令的冷却（单位：秒）
#在这里写上需要添加冷却的命令，可以防止玩家频繁执行命令。
#注意，本功能的判断逻辑是：当玩家输入的命令以列表中的某个命令为开头，就会被添加冷却
#此设置中的命令，其主命令的源头的所有命令别名（包括带前缀的命令）均会添加冷却。
#例如: 为"lce"命令设置冷却时间时，将使 "litecommandeditor:lce", "litecommandeditor:litecommandeditor" 等本插件的所有命令别名都添加相同的冷却时间
#此选项对其他插件的命令也能够生效
Commands-Cooldown:
    Enabled: true
    #命令列表，格式为：“[命令]:[冷却时间]”
    List: 
    - 'examplecommand compound': 1.0 #即玩家输入 "/examplecommand compound ..." 时就会触发1秒冷却
    
#异步线程的设置
#若不清楚这什么是异步线程，请不要修改这个选项！
Async-Thread-Settings: 
    #每一刻的延迟（单位是秒，可以有小数）
    #例：0.1为每秒执行10次，0.05为每秒执行20次，即 20 TPS
    Tick-Delay: 0.1
    #是否自动移除重复的延时任务（延时任务是指包含Delay设置并且在线程池上运行的任务）
    #启用此选项后，以下任务将在重复运行时将移除当前未完成的延时任务:
    #1. ActionBar 动作栏消息（文字动画）
    #2. Title 标题消息（文字动画）
    #3. ClientSound 播放声音（播放乐谱）
    #4. CompoundFunction 复合函数（函数的执行）
    Remove-Duplicate-Delayed-Tasks: true

#计算保留的小数位数
Retaining-Decimal-Places: 2

#PlaceholderAPI设置
PlaceholderAPI:
    #是否使用
    Enabled: true
    #占位符缓存更新的延迟（秒）
    #由于部分占位符需要不断地读取数据库的数据，
    #此选项用于防止频繁调用PAPI占位符对数据库IO造成的巨大负担
    Cache-Update-Delay: 10.0
    #例外的占位符（不进行缓存的）
    Exceptions: []

#是否检查更新
#每天一次，将自动检测插件的最新版本及信息，并汇报给控制台及有拥有对应权限的玩家
#此功能并不会造成服务器产生过多流量（每次检测产生约不到1kb网络流量）
Updater: true

#是否启用Metrics
#详见https://bstats.org/plugin/bukkit/LiteCommandEditor/
Metrics: true

**Comment by GuYuan-V** [comment]
## config.yml
```
#插件前缀
Prefix: '&bLite&3Command&9Editor &f&l>>> '

#插件语言
#可用语言: Simplified-Chinese（简体中文）、Traditional-Chinese（繁體中文）、English
Language: Simplified-Chinese

#禁用的命令
#禁用后，命令将无法使用（命令将不存在），直到下次重启服务器才会重新判断。
#注意：禁用其他插件的命令可能会发生严重的后果，谨慎使用！
#格式：[命令前缀]:[命令名]
#示例：bukkit:plugins 即可禁用/plugins命令
#如果想要知道命令的前缀，可以使用 /litecommandeditor info [命令] 查看。
Disabled-Commands: []

#执行命令的冷却（单位：秒）
#在这里写上需要添加冷却的命令，可以防止玩家频繁执行命令。
#注意，本功能的判断逻辑是：当玩家输入的命令以列表中的某个命令为开头，就会被添加冷却
#此设置中的命令，其主命令的源头的所有命令别名（包括带前缀的命令）均会添加冷却。
#例如: 为"lce"命令设置冷却时间时，将使 "litecommandeditor:lce", "litecommandeditor:litecommandeditor" 等本插件的所有命令别名都添加相同的冷却时间
#此选项对其他插件的命令也能够生效
Commands-Cooldown:
    Enabled: true
    #命令列表，格式为：“[命令]:[冷却时间]”
    List: 
    - 'examplecommand compound': 1.0 #即玩家输入 "/examplecommand compound ..." 时就会触发1秒冷却
    
#异步线程的设置
#若不清楚这什么是异步线程，请不要修改这个选项！
Async-Thread-Settings: 
    #每一刻的延迟（单位是秒，可以有小数）
    #例：0.1为每秒执行10次，0.05为每秒执行20次，即 20 TPS
    Tick-Delay: 0.1
    #是否自动移除重复的延时任务（延时任务是指包含Delay设置并且在线程池上运行的任务）
    #启用此选项后，以下任务将在重复运行时将移除当前未完成的延时任务:
    #1. ActionBar 动作栏消息（文字动画）
    #2. Title 标题消息（文字动画）
    #3. ClientSound 播放声音（播放乐谱）
    #4. CompoundFunction 复合函数（函数的执行）
    Remove-Duplicate-Delayed-Tasks: true

#计算保留的小数位数
Retaining-Decimal-Places: 2

#PlaceholderAPI设置
PlaceholderAPI:
    #是否使用
    Enabled: true
    #占位符缓存更新的延迟（秒）
    #由于部分占位符需要不断地读取数据库的数据，
    #此选项用于防止频繁调用PAPI占位符对数据库IO造成的巨大负担
    Cache-Update-Delay: 10.0
    #例外的占位符（不进行缓存的）
    Exceptions: []

#是否检查更新
#每天一次，将自动检测插件的最新版本及信息，并汇报给控制台及有拥有对应权限的玩家
#此功能并不会造成服务器产生过多流量（每次检测产生约不到1kb网络流量）
Updater: true

#是否启用Metrics
#详见https://bstats.org/plugin/bukkit/LiteCommandEditor/
Metrics: true
```

## Alias.yml 
```
#命令别名设置
#本选项可用于设置命令的使用别名
#以使命令的使用更加简便
#格式:（支持中文）
#   [命令别名]: [原命令]
#   [命令前缀]:[命令别名]: [原命令]
#若不填写命令前缀，则默认为“litecommandeditor”
#按照此格式可自由添加新的命令别名
#注意：建议在更改设置后重启服务器
Aliases:
    #/litecommandeditor reload -> /lcereload
    "lcereload": "litecommandeditor reload"
    #/litecommandeditor info -> /lceinfo
    "lceinfo": "litecommandeditor info"
    #/litecommandeditor load -> /lceload
    "lceload": "litecommandeditor load"
    #/litecommandeditor unload -> /lceunload
    "lceunload": "litecommandeditor unload"
    #/litecommandeditor list -> /lcelist
    "lcelist": "litecommandeditor list"
    #/litecommandeditor listall -> /lcelistall
    "lcelistall": "litecommandeditor listall"
    #/tpaccept
    "yes": "tpaccept"
    "同意": "tpaccept"
    "y": "tpaccept"
    #/tpdeny
    "n": "tpdeny"
    "no": "tpdeny"
    "拒绝": "tpdeny"
    #/la view help
    "ushelp": "la view help"
    "cnhelp": "la view cnhelp"
    #/tpacancel
    "off": "tpacancel"
    "取消": "tpacancel"
    #/fp spawn
    minecraft:setjr: fp spawn
    "创建假人": "fp spawn"
    #/fp kill
    "offjr": "fp kill"
    "清除假人": "fp kill"
    #/tab player 
    "qtab": "tab player"
    #/fp status
    "lookjr": "fp status"
    "查看假人": "fp status"
```
